on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  DOCKER_VER: "2.3a"
  DOCKER_TAG: "repasscloud/optechx.portal"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      # - name: setup docker on macos-latest
      #   run: |
      #     HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
      #     sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
      #     open -a /Applications/Docker.app --args --unattended --accept-license
      #     echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
      #     while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
      #   shell: bash

      - name: Setup
        run: ./setup.sh
        env:
          DTAG: ${{ env.DOCKER_TAG }}
          DVER: ${{ env.DOCKER_VER }}
        shell: bash

      # - name: Archive package-lock.json
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: package-lock
      #     path: output/test/code-coverage.html