on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_VER: "2.2"
  DOCKER_TAG: "repasscloud/optechx.portal"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: ./setup.sh
        env:
          DTAG: ${{ env.DOCKER_TAG }}
          DVER: ${{ env.DOCKER_VER }}
        shell: bash

